/**
 * Tiranga Cable TV & Internet - Complaint Management Module (Phase B)
 * ====================================================================
 * CRUD operations for the complaints table via Supabase.
 * Dependencies: config.js, supabase-client.js, auth.js, roles.js
 *
 * Security notes:
 *   - complaint_id is generated by the database (CMP-0001, CMP-0002, ...).
 *   - created_by / customer_id are resolved server-side from the session,
 *     so a customer can never file a complaint in someone else's name.
 *   - Row Level Security restricts customers to their own complaints.
 */

const TirangaComplaints = (function () {
  'use strict';

  const CATEGORIES = [
    'Internet Not Working',
    'Slow Internet',
    'Cable TV Not Working',
    'Signal Issue',
    'Installation Issue',
    'Payment Issue',
    'Other',
  ];

  const PRIORITIES = ['low', 'medium', 'high', 'urgent'];

  const STATUSES = ['pending', 'assigned', 'in_progress', 'resolved', 'closed'];

  const STATUS_LABELS = {
    pending: 'Pending',
    assigned: 'Assigned',
    in_progress: 'In Progress',
    resolved: 'Resolved',
    closed: 'Closed',
  };

  const PRIORITY_LABELS = {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
  };

  // Columns plus related customer / reporter / technician records.
  // The relationships are named after the foreign-key columns because
  // complaints has two references into profiles.
  const SELECT_WITH_RELATIONS =
    '*, customer:customer_id(id, customer_id, full_name, phone, area), ' +
    'reporter:created_by(id, full_name, phone), ' +
    'technician:technician_id(id, full_name, phone)';

  const SELECT_BASIC = '*';

  function noClient() {
    return { success: false, error: 'Supabase client not initialized. Check js/config.js.' };
  }

  /**
   * Run a select that embeds related rows, falling back to a plain
   * select when the embedded relationships are unavailable (for example
   * when the customers table has not been linked yet).
   * @param {function} build - receives the select string, returns a query
   * @returns {Promise<Array>}
   */
  async function selectWithFallback(build) {
    let { data, error } = await build(SELECT_WITH_RELATIONS);

    if (error) {
      console.warn('[Complaints] Embedded select failed, retrying without relations:', error.message);
      ({ data, error } = await build(SELECT_BASIC));
    }

    if (error) {
      console.error('[Complaints] Fetch error:', error.message);
      throw new Error(error.message);
    }

    return data || [];
  }

  /**
   * Submit a new complaint for the signed-in customer.
   * @param {{category: string, description: string, priority: string}} input
   * @returns {Promise<{success: boolean, data?: object, error?: string}>}
   */
  async function create(input) {
    if (!tirangaSupabase) return noClient();

    const category = (input.category || '').trim();
    const description = (input.description || '').trim();
    const priority = (input.priority || 'medium').trim();

    if (!CATEGORIES.includes(category)) {
      return { success: false, error: 'Please choose a valid complaint category.' };
    }
    if (!description) {
      return { success: false, error: 'Please describe the problem.' };
    }
    if (!PRIORITIES.includes(priority)) {
      return { success: false, error: 'Please choose a valid priority.' };
    }

    try {
      const user = await TirangaAuth.getCurrentUser();
      if (!user) {
        return { success: false, error: 'Your session has expired. Please sign in again.' };
      }

      const { data, error } = await tirangaSupabase
        .from('complaints')
        .insert([{ category, description, priority, created_by: user.id }])
        .select(SELECT_BASIC)
        .single();

      if (error) {
        console.error('[Complaints] Create error:', error.message);
        return { success: false, error: error.message };
      }

      return { success: true, data };
    } catch (err) {
      console.error('[Complaints] create failed:', err);
      return { success: false, error: err.message || 'Failed to submit complaint.' };
    }
  }

  /**
   * Complaints filed by the signed-in user, newest first.
   * @returns {Promise<Array>}
   */
  async function getMine() {
    if (!tirangaSupabase) throw new Error('Supabase client not initialized.');

    const user = await TirangaAuth.getCurrentUser();
    if (!user) throw new Error('Your session has expired. Please sign in again.');

    return await selectWithFallback((cols) =>
      tirangaSupabase
        .from('complaints')
        .select(cols)
        .eq('created_by', user.id)
        .order('created_at', { ascending: false })
    );
  }

  /**
   * All complaints visible to the signed-in admin.
   * @param {{search?: string, status?: string, priority?: string}} filters
   * @returns {Promise<Array>}
   */
  async function getAll(filters = {}) {
    if (!tirangaSupabase) throw new Error('Supabase client not initialized.');

    const rows = await selectWithFallback((cols) => {
      let query = tirangaSupabase
        .from('complaints')
        .select(cols)
        .order('created_at', { ascending: false });

      if (filters.status) query = query.eq('status', filters.status);
      if (filters.priority) query = query.eq('priority', filters.priority);
      if (filters.category) query = query.eq('category', filters.category);

      return query;
    });

    // Search is applied client-side because it spans embedded customer fields.
    const search = (filters.search || '').trim().toLowerCase();
    if (!search) return rows;

    return rows.filter((c) => {
      const haystack = [
        c.complaint_id,
        c.category,
        c.description,
        c.customer && c.customer.full_name,
        c.customer && c.customer.phone,
        c.customer && c.customer.area,
        c.reporter && c.reporter.full_name,
        c.reporter && c.reporter.phone,
      ]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();
      return haystack.includes(search);
    });
  }

  /**
   * A single complaint by UUID.
   * @param {string} id
   * @returns {Promise<object|null>}
   */
  async function getById(id) {
    if (!tirangaSupabase) throw new Error('Supabase client not initialized.');

    const rows = await selectWithFallback((cols) =>
      tirangaSupabase.from('complaints').select(cols).eq('id', id).limit(1)
    );

    return rows[0] || null;
  }

  /**
   * Update status / priority / technician assignment. Admin only (enforced by RLS).
   * @param {string} id
   * @param {{status?: string, priority?: string, technician_id?: string|null}} updates
   * @returns {Promise<{success: boolean, data?: object, error?: string}>}
   */
  async function update(id, updates) {
    if (!tirangaSupabase) return noClient();

    const payload = {};
    if (updates.status !== undefined) {
      if (!STATUSES.includes(updates.status)) {
        return { success: false, error: 'Invalid status value.' };
      }
      payload.status = updates.status;
    }
    if (updates.priority !== undefined) {
      if (!PRIORITIES.includes(updates.priority)) {
        return { success: false, error: 'Invalid priority value.' };
      }
      payload.priority = updates.priority;
    }
    if (updates.technician_id !== undefined) {
      payload.technician_id = updates.technician_id || null;
    }

    if (!Object.keys(payload).length) {
      return { success: false, error: 'Nothing to update.' };
    }

    try {
      const { data, error } = await tirangaSupabase
        .from('complaints')
        .update(payload)
        .eq('id', id)
        .select(SELECT_BASIC)
        .single();

      if (error) {
        console.error('[Complaints] Update error:', error.message);
        return { success: false, error: error.message };
      }

      return { success: true, data };
    } catch (err) {
      console.error('[Complaints] update failed:', err);
      return { success: false, error: err.message || 'Failed to update complaint.' };
    }
  }

  /**
   * Dashboard counters computed from the complaints the caller can see.
   * @param {Array} [rows] - optional pre-fetched complaints
   * @returns {Promise<{total, pending, assigned, in_progress, resolved, urgent}>}
   */
  async function getStats(rows) {
    const all = rows || (await getAll());
    const countBy = (key, value) => all.filter((c) => c[key] === value).length;

    return {
      total: all.length,
      pending: countBy('status', 'pending'),
      assigned: countBy('status', 'assigned'),
      in_progress: countBy('status', 'in_progress'),
      resolved: countBy('status', 'resolved'),
      urgent: countBy('priority', 'urgent'),
    };
  }

  /**
   * Technicians available for assignment.
   *
   * Phase B has no technician module yet, so technicians are read from the
   * existing profiles table (role = 'technician'). When the dedicated
   * technician table lands, only this function needs to change.
   * @returns {Promise<Array<{id: string, full_name: string}>>}
   */
  async function getTechnicians() {
    if (!tirangaSupabase) return [];

    try {
      const { data, error } = await tirangaSupabase
        .from('profiles')
        .select('id, full_name, phone')
        .eq('role', 'technician')
        .eq('status', 'active')
        .order('full_name', { ascending: true });

      if (error) {
        console.warn('[Complaints] Could not load technicians:', error.message);
        return [];
      }

      return data || [];
    } catch (err) {
      console.warn('[Complaints] getTechnicians failed:', err);
      return [];
    }
  }

  /** Display name of the complaining customer, with profile fallback. */
  function customerName(c) {
    if (c.customer && c.customer.full_name) return c.customer.full_name;
    if (c.reporter && c.reporter.full_name) return c.reporter.full_name;
    return '—';
  }

  /** Display phone of the complaining customer, with profile fallback. */
  function customerPhone(c) {
    if (c.customer && c.customer.phone) return c.customer.phone;
    if (c.reporter && c.reporter.phone) return c.reporter.phone;
    return '—';
  }

  /** Display area of the complaining customer. */
  function customerArea(c) {
    if (c.customer && c.customer.area) return c.customer.area;
    return '—';
  }

  /** Display name of the assigned technician. */
  function technicianName(c) {
    if (c.technician && c.technician.full_name) return c.technician.full_name;
    if (c.technician_id) return 'Assigned';
    return 'Unassigned';
  }

  /** Format a timestamp for the UI. */
  function formatDate(value) {
    if (!value) return '—';
    const d = new Date(value);
    if (isNaN(d.getTime())) return '—';
    return d.toLocaleString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  return {
    CATEGORIES,
    PRIORITIES,
    STATUSES,
    STATUS_LABELS,
    PRIORITY_LABELS,
    create,
    getMine,
    getAll,
    getById,
    update,
    getStats,
    getTechnicians,
    customerName,
    customerPhone,
    customerArea,
    technicianName,
    formatDate,
  };
})();
