-- ============================================================================
-- Tiranga Connect — Phase C1: Technician Management (database foundation)
--
-- Creates public.technicians, its readable TRG-TECH-#### identifier, RLS and
-- indexes. Nothing from Phase A (customers) or Phase B (complaints) is
-- modified, dropped or re-created.
--
-- Safe to run more than once.
-- Run this in the Supabase SQL Editor.
-- ============================================================================

-- ── Admin authorization helper ──────────────────────────────────────────────
-- The project already ships a recursion-safe admin check. Reuse whichever one
-- the database has (public.is_admin() is preferred, public.tiranga_is_admin()
-- is the Phase B fallback) and only create it when neither exists, so an
-- existing definition is never overwritten.
DO $$
BEGIN
  IF to_regprocedure('public.is_admin()') IS NULL
     AND to_regprocedure('public.tiranga_is_admin()') IS NULL THEN
    EXECUTE $fn$
      CREATE FUNCTION public.is_admin()
      RETURNS BOOLEAN
      LANGUAGE sql
      STABLE
      SECURITY DEFINER
      SET search_path = public, pg_temp
      AS $body$
        SELECT EXISTS (
          SELECT 1
          FROM public.profiles p
          WHERE p.id = auth.uid()
            AND p.role = 'admin'
            AND p.status = 'active'
        );
      $body$;
    $fn$;
  END IF;
END;
$$;

-- Name of the admin helper this migration will reference in its policies.
CREATE OR REPLACE FUNCTION public.tiranga_admin_check_expr()
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN to_regprocedure('public.is_admin()') IS NOT NULL THEN 'public.is_admin()'
    ELSE 'public.tiranga_is_admin()'
  END;
$$;

COMMENT ON FUNCTION public.tiranga_admin_check_expr() IS
  'Returns the name of the recursion-safe admin predicate used when building RLS policies.';

-- ── Technician identifier ───────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS public.technician_id_seq START WITH 1 INCREMENT BY 1;

COMMENT ON SEQUENCE public.technician_id_seq IS
  'Backs the readable TRG-TECH-#### technician identifier. Concurrency-safe.';

CREATE OR REPLACE FUNCTION public.generate_technician_id()
RETURNS TEXT
LANGUAGE sql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT 'TRG-TECH-' || lpad(nextval('public.technician_id_seq')::TEXT, 4, '0');
$$;

COMMENT ON FUNCTION public.generate_technician_id() IS
  'Next technician identifier, e.g. TRG-TECH-0001. Sequence-backed, so it stays unique under concurrent inserts.';

-- Only signed-in admins ever insert technicians; anonymous visitors must not be
-- able to burn identifiers by calling the function directly.
REVOKE ALL ON FUNCTION public.generate_technician_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_technician_id() TO authenticated;

-- ── Table ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.technicians (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id      UUID NOT NULL UNIQUE
                    REFERENCES public.profiles(id) ON DELETE CASCADE,
  technician_id   TEXT NOT NULL UNIQUE DEFAULT public.generate_technician_id(),
  full_name       TEXT NOT NULL CHECK (length(btrim(full_name)) > 0),
  phone           TEXT NOT NULL CHECK (length(btrim(phone)) > 0),
  alternate_phone TEXT,
  address         TEXT,
  area            TEXT NOT NULL CHECK (length(btrim(area)) > 0),
  status          TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'inactive', 'suspended')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.technicians IS
  'Field technicians. One row per profiles row with role = technician (Phase C1).';
COMMENT ON COLUMN public.technicians.profile_id IS
  'Owning auth user; unique, so a profile can back at most one technician record.';
COMMENT ON COLUMN public.technicians.technician_id IS
  'Human-readable identifier (TRG-TECH-0001) generated by public.generate_technician_id().';
COMMENT ON COLUMN public.technicians.area IS
  'Service area the technician covers; used later for complaint assignment.';
COMMENT ON COLUMN public.technicians.status IS
  'active | inactive | suspended — only active technicians are assignable.';

-- ── updated_at ──────────────────────────────────────────────────────────────
-- public.handle_updated_at() already exists (profiles_setup.sql); it is reused
-- as-is and only created when missing.
DO $$
BEGIN
  IF to_regprocedure('public.handle_updated_at()') IS NULL THEN
    EXECUTE $fn$
      CREATE FUNCTION public.handle_updated_at()
      RETURNS TRIGGER
      LANGUAGE plpgsql
      SET search_path = public, pg_temp
      AS $body$
      BEGIN
        NEW.updated_at = now();
        RETURN NEW;
      END;
      $body$;
    $fn$;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS technicians_updated_at ON public.technicians;
CREATE TRIGGER technicians_updated_at
  BEFORE UPDATE ON public.technicians
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- ── Indexes ─────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS technicians_profile_id_idx    ON public.technicians (profile_id);
CREATE INDEX IF NOT EXISTS technicians_technician_id_idx ON public.technicians (technician_id);
CREATE INDEX IF NOT EXISTS technicians_area_idx          ON public.technicians (area);
CREATE INDEX IF NOT EXISTS technicians_status_idx        ON public.technicians (status);
CREATE INDEX IF NOT EXISTS technicians_phone_idx         ON public.technicians (phone);

-- ── Row Level Security ──────────────────────────────────────────────────────
-- No policy reads public.technicians, and the admin predicate is a
-- SECURITY DEFINER function, so RLS on profiles is never re-entered — the
-- recursion problem previously hit on public.profiles cannot occur here.
ALTER TABLE public.technicians ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  admin_check TEXT := public.tiranga_admin_check_expr();
BEGIN
  DROP POLICY IF EXISTS "Technicians can view own record" ON public.technicians;
  DROP POLICY IF EXISTS "Admins can view all technicians" ON public.technicians;
  DROP POLICY IF EXISTS "Admins can insert technicians"   ON public.technicians;
  DROP POLICY IF EXISTS "Admins can update technicians"   ON public.technicians;
  DROP POLICY IF EXISTS "Admins can delete technicians"   ON public.technicians;

  EXECUTE 'CREATE POLICY "Technicians can view own record" ON public.technicians
             FOR SELECT TO authenticated
             USING (profile_id = auth.uid())';

  EXECUTE format('CREATE POLICY "Admins can view all technicians" ON public.technicians
                    FOR SELECT TO authenticated
                    USING (%s)', admin_check);

  EXECUTE format('CREATE POLICY "Admins can insert technicians" ON public.technicians
                    FOR INSERT TO authenticated
                    WITH CHECK (%s)', admin_check);

  EXECUTE format('CREATE POLICY "Admins can update technicians" ON public.technicians
                    FOR UPDATE TO authenticated
                    USING (%1$s) WITH CHECK (%1$s)', admin_check);

  EXECUTE format('CREATE POLICY "Admins can delete technicians" ON public.technicians
                    FOR DELETE TO authenticated
                    USING (%s)', admin_check);
END;
$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.technicians TO authenticated;

-- No seed data: technicians are created by an admin through the UI in C2.
