-- ============================================================
-- TIRANGA CABLE TV & INTERNET
-- Supabase Database Setup: Complaints Table (Phase B)
-- ============================================================
--
-- INSTRUCTIONS:
-- 1. Go to your Supabase Dashboard
-- 2. Navigate to SQL Editor -> New query
-- 3. Paste and run this ENTIRE script
-- 4. Verify: Table Editor should now show a `complaints` table
--
-- This script is idempotent: it can safely be run more than once.
-- It does NOT touch the existing `profiles` or `customers` tables
-- (other than reading their structure to wire up foreign keys).
--
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- 1. ADMIN AUTHORIZATION HELPER (recursion-safe)
-- ────────────────────────────────────────────────────────────
-- RLS policies must NEVER read a table from inside that same
-- table's policy (that is what caused the infinite recursion on
-- `profiles`). A SECURITY DEFINER function runs with the owner's
-- rights and therefore bypasses RLS, so reading `profiles` from
-- inside it is safe and non-recursive.
--
-- A dedicated name (`tiranga_is_admin`) is used so that any
-- pre-existing admin helper in your database is left untouched.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.tiranga_is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
      AND p.status = 'active'
  );
$$;

COMMENT ON FUNCTION public.tiranga_is_admin() IS
  'Returns true when the calling user is an active admin. SECURITY DEFINER so RLS policies can call it without recursing into profiles.';

REVOKE ALL ON FUNCTION public.tiranga_is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.tiranga_is_admin() TO authenticated;


-- ────────────────────────────────────────────────────────────
-- 2. COMPLAINTS TABLE
-- ────────────────────────────────────────────────────────────
-- `created_by` is the ownership anchor used by RLS: it is always
-- the authenticated user who filed the complaint and can never be
-- forged from the browser (default auth.uid() + WITH CHECK).
--
-- `customer_id` points at the matching row in `public.customers`
-- and is resolved server-side (see section 4), never sent by the
-- frontend.
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.complaints (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_id  TEXT UNIQUE,
  customer_id   UUID,
  created_by    UUID NOT NULL DEFAULT auth.uid()
                  REFERENCES public.profiles(id) ON DELETE CASCADE,
  category      TEXT NOT NULL CHECK (category IN (
                  'Internet Not Working',
                  'Slow Internet',
                  'Cable TV Not Working',
                  'Signal Issue',
                  'Installation Issue',
                  'Payment Issue',
                  'Other'
                )),
  description   TEXT NOT NULL CHECK (length(btrim(description)) > 0),
  priority      TEXT NOT NULL DEFAULT 'medium'
                  CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'assigned', 'in_progress', 'resolved', 'closed')),
  technician_id UUID,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at   TIMESTAMPTZ
);

COMMENT ON TABLE  public.complaints IS 'Customer complaints for Tiranga Cable TV & Internet (Phase B).';
COMMENT ON COLUMN public.complaints.complaint_id IS 'Human readable ID generated by the database, e.g. CMP-0001.';
COMMENT ON COLUMN public.complaints.created_by IS 'profiles.id (= auth.users.id) of the person who filed the complaint. Ownership anchor for RLS, and the fallback source of customer name/phone in the admin UI.';
COMMENT ON COLUMN public.complaints.customer_id IS 'public.customers.id of the complaining customer, resolved server-side from created_by.';
COMMENT ON COLUMN public.complaints.technician_id IS 'Assigned technician. Nullable placeholder until the Technician module exists.';

-- Foreign keys that depend on the pre-existing schema.
-- They are only created when the referenced table/column is present,
-- so this script works whether or not the technician module exists yet.
DO $$
BEGIN
  -- complaints.customer_id -> public.customers(id)
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'customers'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'complaints_customer_id_fkey'
  ) THEN
    ALTER TABLE public.complaints
      ADD CONSTRAINT complaints_customer_id_fkey
      FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
  END IF;

  -- complaints.technician_id -> public.profiles(id)
  -- Technicians are represented as profiles with role = 'technician'
  -- until a dedicated technicians table is introduced.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'complaints_technician_id_fkey'
  ) THEN
    ALTER TABLE public.complaints
      ADD CONSTRAINT complaints_technician_id_fkey
      FOREIGN KEY (technician_id) REFERENCES public.profiles(id) ON DELETE SET NULL;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_complaints_created_by  ON public.complaints(created_by);
CREATE INDEX IF NOT EXISTS idx_complaints_customer_id ON public.complaints(customer_id);
CREATE INDEX IF NOT EXISTS idx_complaints_status      ON public.complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_priority    ON public.complaints(priority);
CREATE INDEX IF NOT EXISTS idx_complaints_created_at  ON public.complaints(created_at DESC);


-- ────────────────────────────────────────────────────────────
-- 3. READABLE COMPLAINT ID (CMP-0001, CMP-0002, ...)
-- ────────────────────────────────────────────────────────────
-- Generated by the database from a sequence, so concurrent
-- submissions can never collide and the frontend cannot choose
-- its own ID.
-- ────────────────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS public.complaint_id_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION public.generate_complaint_id()
RETURNS TEXT
LANGUAGE sql
VOLATILE
AS $$
  SELECT 'CMP-' || lpad(nextval('public.complaint_id_seq')::TEXT, 4, '0');
$$;

COMMENT ON FUNCTION public.generate_complaint_id() IS 'Returns the next readable complaint ID, e.g. CMP-0007.';


-- ────────────────────────────────────────────────────────────
-- 4. INSERT TRIGGER: assign complaint_id + resolve customer_id
-- ────────────────────────────────────────────────────────────
-- Anything a customer might try to forge is overwritten here:
--   * complaint_id  -> always generated by the database
--   * created_by    -> always the authenticated user
--   * customer_id   -> always resolved from created_by
--   * status        -> always starts as 'pending'
--
-- `customers` is linked to auth users through whichever column the
-- existing schema uses; the lookup below probes the common names and
-- silently leaves customer_id NULL when no link column exists (the
-- admin UI then falls back to the profile name/phone).
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.tiranga_resolve_customer_id(p_user_id UUID)
RETURNS UUID
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_link_column TEXT;
  v_customer_id UUID;
BEGIN
  IF p_user_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT column_name INTO v_link_column
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'customers'
    AND column_name IN ('user_id', 'profile_id', 'auth_user_id', 'auth_id', 'id')
  ORDER BY array_position(
    ARRAY['user_id', 'profile_id', 'auth_user_id', 'auth_id'], column_name
  ) NULLS LAST
  LIMIT 1;

  -- `id` is only usable as a link when customers.id IS the auth user id,
  -- which is not the case in this schema, so ignore it.
  IF v_link_column IS NULL OR v_link_column = 'id' THEN
    RETURN NULL;
  END IF;

  EXECUTE format(
    'SELECT id FROM public.customers WHERE %I = $1 LIMIT 1', v_link_column
  ) INTO v_customer_id USING p_user_id;

  RETURN v_customer_id;
END;
$$;

COMMENT ON FUNCTION public.tiranga_resolve_customer_id(UUID) IS
  'Maps an auth.users.id to the matching public.customers.id, or NULL when the customers table has no auth link column.';

REVOKE ALL ON FUNCTION public.tiranga_resolve_customer_id(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.tiranga_resolve_customer_id(UUID) TO authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_complaint()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.complaint_id := public.generate_complaint_id();

  IF auth.uid() IS NOT NULL THEN
    NEW.created_by := auth.uid();
  END IF;

  IF NEW.customer_id IS NULL THEN
    NEW.customer_id := public.tiranga_resolve_customer_id(NEW.created_by);
  END IF;

  NEW.status      := 'pending';
  NEW.created_at  := now();
  NEW.updated_at  := now();
  NEW.resolved_at := NULL;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_complaint_created ON public.complaints;
CREATE TRIGGER on_complaint_created
  BEFORE INSERT ON public.complaints
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_complaint();


-- ────────────────────────────────────────────────────────────
-- 5. UPDATE TRIGGER: updated_at + resolved_at bookkeeping
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_complaint_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- Identity fields can never be changed after creation.
  NEW.id           := OLD.id;
  NEW.complaint_id := OLD.complaint_id;
  NEW.created_by   := OLD.created_by;
  NEW.created_at   := OLD.created_at;

  NEW.updated_at := now();

  IF NEW.status IN ('resolved', 'closed') AND OLD.status NOT IN ('resolved', 'closed') THEN
    NEW.resolved_at := now();
  ELSIF NEW.status NOT IN ('resolved', 'closed') THEN
    NEW.resolved_at := NULL;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_complaint_updated ON public.complaints;
CREATE TRIGGER on_complaint_updated
  BEFORE UPDATE ON public.complaints
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_complaint_update();


-- ────────────────────────────────────────────────────────────
-- 6. ROW LEVEL SECURITY
-- ────────────────────────────────────────────────────────────
-- No policy below reads `public.complaints`, so the infinite
-- recursion problem seen on `profiles` cannot occur here.
--
-- Admin scope: this deployment serves a single LCO, so an admin
-- sees every complaint in the database. When multi-LCO support is
-- added, extend the admin policies with an lco_id predicate.
-- ────────────────────────────────────────────────────────────
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Customers can create own complaints"  ON public.complaints;
DROP POLICY IF EXISTS "Customers can view own complaints"    ON public.complaints;
DROP POLICY IF EXISTS "Admins can view all complaints"       ON public.complaints;
DROP POLICY IF EXISTS "Admins can update all complaints"     ON public.complaints;

-- CUSTOMER: may file a complaint only in their own name
CREATE POLICY "Customers can create own complaints"
  ON public.complaints
  FOR INSERT
  TO authenticated
  WITH CHECK (created_by = auth.uid());

-- CUSTOMER: may read only their own complaints
CREATE POLICY "Customers can view own complaints"
  ON public.complaints
  FOR SELECT
  TO authenticated
  USING (created_by = auth.uid());

-- ADMIN: may read every complaint
CREATE POLICY "Admins can view all complaints"
  ON public.complaints
  FOR SELECT
  TO authenticated
  USING (public.tiranga_is_admin());

-- ADMIN: may change status, priority and technician assignment
CREATE POLICY "Admins can update all complaints"
  ON public.complaints
  FOR UPDATE
  TO authenticated
  USING (public.tiranga_is_admin())
  WITH CHECK (public.tiranga_is_admin());

-- Deliberately no DELETE policy: complaints are never deleted in Phase B.

GRANT SELECT, INSERT, UPDATE ON public.complaints TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.complaint_id_seq TO authenticated;


-- ────────────────────────────────────────────────────────────
-- 7. ADMIN READ ACCESS TO CUSTOMER CONTACT DETAILS
-- ────────────────────────────────────────────────────────────
-- The admin complaints table shows customer name / phone / area.
-- Those come from `customers` (or `profiles` as a fallback) and rely
-- on the RLS already configured for those tables in earlier phases.
-- Nothing is changed here on purpose.
-- ============================================================
